### ISSUE TITLE
Escaped brackets containing code

### ISSUE THREAD

**Issue by KyleKing** [hukkin/mdformat#493]
### Describe the bug

**context:**
`[`code`]`

Real world example: https://github.com/astral-sh/ruff/blob/a623d8f7c44cd63897489cad0faed1538d4373c8/CONTRIBUTING.md?plain=1#L85-L87

**expectation:**
Brackets are not escaped

I'll work on a fix this week

### Reproduce the bug

```console
> echo '[not-code] vs. [`code`]' | uvx --with='mdformat==0.7.19' mdformat -
[not-code] vs. \[`code`\] 
```

### List your environment

0.7.19

**Comment by hukkin** [comment]
Thanks for the issue!

I don't consider this a bug, as the added backslashes don't change rendered HTML in any way.

This happens because the logic that avoids adding backslashes in [special cases](https://github.com/hukkin/mdformat/issues/112#issuecomment-814880958) only looks at `text` syntax, but the square bracketed text is `code_inline` syntax so `text` renderer never sees it.

Not sure, but perhaps that logic can be moved to one step higher level, i.e. the renderer for `inline` syntax. I haven't thought about that much, but such a change is potentially dangerous as the `inline` renderer receives content that should never be backslash escaped (`code_inline` is one such example).

**Comment by KyleKing** [comment]
Okay, then I agree that changing the behavior would not be worthwhile
